replicaCount: 1

image:
  repository: docker.io/hanna22222/App_Kub
  tag: "dev-v0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true 
  host: app-kub.example.com 
  tlsSecretName: app-kub-tls
