apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-kub
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-kub
  template:
    metadata:
      labels:
        app: app-kub
    spec:
      containers:
        - name: app-kub
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
